"""change avatar_url to text

Revision ID: 6f9256badfec
Revises: 1e78f68f8ee0
Create Date: 2026-01-03 10:55:56.459201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9256badfec'
down_revision = '1e78f68f8ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('activities_itinerary_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'itineraries', ['itinerary_id'], ['id'])

    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('itineraries_trip_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'trips', ['trip_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar_url',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)

    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('itineraries_trip_id_fkey'), 'trips', ['trip_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('activities_itinerary_id_fkey'), 'itineraries', ['itinerary_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
